### DISCUSSION TITLE
State of Dev 2023 Call for Questions and Suggestions

### DISCUSSION THREAD

**Discussion by yjose** [DevC-Casa/stateofdev.ma#105] [Ideas]
The State of Dev in Morocco 2023 is coming up, and we want to hear from you! We're looking for new questions and suggestions, as well as recommendations to improve survey reach and participation for this year's edition

This discussion will be open until November 30, 2023. After that, we will do our best to review suggestions and apply them to ensure that we can open the survey to the public on December 3, 2023 (the first Geeksblabla episode of December).

##  🙌 How you can help ?

First of all, we want to thank you for your interest in helping us improve the State of Dev in Morocco. and here are some ways you can help:

###  ⁉️ Survey Questions and Answers

[State of Dev in Morocco 2022 Report](https://stateofdev.ma/)

Last Year's Survey Questions and Answers 👇

<details>
  <summary>Profile</summary>

```yaml
title: Profile
label: profile
position: 1
questions:
  - label: What is your gender?
    required: true
    multiple: false
    choices:
      - Male
      - Female

  - label: What is your age?
    required: true
    choices:
      - Younger than 18 years
      - 18 to 24 years
      - 25 to 34 years
      - 35 to 44 years
      - 45 or older

  - label: Where are you currently located?
    required: true
    choices:
      - "Rabat-Salé-Kénitra"
      - "Casablanca-Settat"
      - "Marrakech-Safi"
      - "Tanger-Tétouan-Al Hoceïma"
      - "L'Oriental"
      - "Fès-Meknès"
      - "Béni Mellal-Khénifra"
      - "Drâa-Tafilalet"
      - "Souss-Massa"
      - "Guelmim-Oued Noun"
      - "Laâyoune-Sakia El Hamra"
      - "Dakhla-Oued Ed Dahab"
      - Europe
      - "US & Canada"
      - "Middle East"
      - Others

  - label: What is your occupation?
    required: true
    choices:
      - Back-end developer
      - Full-stack developer
      - Front-end developer
      - Desktop applications developer
      - Mobile developer
      - Embedded applications/devices developer
      - QA/test Develper
      - Game/graphics Developer
      - DevOps specialist
      - Database administrator
      - Designer
      - System administrator
      - Data/business analyst
      - Data scientist or machine learning specialist
      - Data engineer
      - Academic researcher
      - Educator
      - Engineering manager
      - Product manager
      - Scientist
      - Site reliability engineer
      - Senior executive/VP
      - Marketing/sales professional
      - Network engineer
      - Security specialist
      - IT specialist

  - label: What is your highest diploma?
    required: true
    choices:
      - Self-taught
      - Bac +2/+3, Bachelor’s degree (B.A., B.S., B.Eng., etc.)
      - Bac +5, Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
      - Bac +8, Other doctoral degree (Ph.D., Ed.D., etc.)

  - label: How many years have you been coding professionally?
    required: true
    choices:
      - "I don't have any professional coding experience"
      - Less than a year
      - 1-2 years
      - 3-4 years
      - 5-6 years
      - 7-10 years
      - 11-16 years
      - 16+ years

  - label: Is coding a hobby for you?
    required: true
    choices:
      - Yes
      - No

  - label: Do you have any plans to work outside Morocco?
    required: true
    choices:
      - Yes, in the next 12 months
      - Yes, in the next 24 months
      - Still hesitating
      - Currently working outside Morocco
      - No

  - label: If you are working abroad, do you have any plans to come back to Morocco?
    choices:
      - Yes
      - Still hesitating
      - No

  - label: What do you usually drink while coding?
    required: true
    choices:
      - Tea
      - Coffee
      - Water
      - Energy drinks
      - None
      - Other
```

</details>

<details>
  <summary>Learning & Education</summary>

```yaml
title: Learning & Education
label: education
position: 2
questions:
  - label: Where did you study coding?
    required: true
    multiple: true
    choices:
      - Self-taught
      - University / Public school
      - Private school
      - Vocational School (bootcamps, technical skills  ...)
      - Other

  - label: Do you think school gives you enough knowledge to start your professional career?
    required: true
    choices:
      - Not enough
      - Enough to start
      - Everything I needed

  - label: If you think we have a problem with our education system, from your point of view, who are the main contributors?
    required: true
    multiple: true
    choices:
      - Students level
      - Teachers proficiency
      - Academic defined subjects (system)
      - Lack of private sector/academia collaboration

  - label: What languages can you read/write?
    required: true
    multiple: true
    choices:
      - Arabic
      - Amazigh
      - French
      - English
      - Others

  - label: Is English an obstacle to learning new technologies?
    required: true
    choices:
      - Yes
      - No

  - label: Do you think we need more content in Darija?
    required: true
    choices:
      - Spoken
      - Written/Read
      - Both
      - No

  - label: What are your preferred platforms for learning?
    required: true
    multiple: true
    choices:
      - YouTube
      - Paid platforms
      - Books
      - Official documentation
      - Blog posts
      - Company resources
      - Conferences (virtual/in-person)
      - Podcasts
      - Online Communities (StackOverflow/Reddit/Twitter)
      - Others
```
</details>

<details>
  <summary>Work</summary>

```yaml
title: Work
label: work
position: 3
questions:
  - label: "What is your employment status?"
    required: true
    multiple: false
    choices:
      - Founder/entrepreneur
      - Employed full-time
      - Freelancer/self-employed
      - Employed part-time
      - Looking for work
      - Internship
      - Student

  - label: How often do you work overtime or beyond the formal time expectation of your job?
    choices:
      - Never
      - "Rarely: 1-2 days per year or less "
      - "Occasionally: 1-2 days per quarter but less than monthly "
      - "Sometimes: 1-2 days per month but less than weekly"
      - "Often: 1-2 days per week or more"

  - label: How do you feel about your job?
    choices:
      - Very Unsatisfied
      - Slightly Unsatisfied
      - Neither satisfied nor Unsatisfied
      - Slightly satisfied
      - Very satisfied

  - label: Do you work on a side project?
    required: true
    choices:
      - No
      - Yes For profit
      - Yes For learning

  - label: How long have you been unemployed after graduation?
    choices:
      - None, I worked straight after my graduation 😎
      - Up to 3 months
      - Up to 6 months
      - Up to 1 year
      - More than 1 year

  - label: "If you are working full-time contract in Morocco(CDI), Your NET salary range per month in MAD is:"
    choices:
      - "< 4 000"
      - "4 000 - 6 000"
      - "6 000 - 8 000"
      - "8 000 - 10 000"
      - "10 000 - 12 000"
      - "12 000 - 14 000"
      - "14 000 - 16 000"
      - "16 000 - 18 000"
      - "18 000 - 20 000"
      - "20 000 - 22 000"
      - "22 000 - 25 000"
      - "25 000 - 30 000"
      - "> 30 000"

  - label: "If you are working as a freelancer in Morocco, Your salary range per day in MAD(TJM) is:"
    choices:
      - "< 1 000"
      - "1 000 - 1 500"
      - "1 500 - 2 000"
      - "2 000 - 2 500"
      - "2 500 - 3 000"
      - "3 000 - 4 000"
      - "4 000 - 5 000"
      - "> 5 000"

  - label: "If you are working full-time contract outside Morocco, Your gross salary range per year in USD is:"
    choices:
      - "< 20 000"
      - "20 000 - 25 000"
      - "30 500 - 40 000"
      - "40 000 - 50 000"
      - "50 000 - 60 000"
      - "60 000 - 80 000"
      - "80 000 - 100 000"
      - "100 000 - 120 000"
      - "120 000 - 150 000"
      - "150 000 - 200 000"
      - "> 200 000"

  - label: "If you are working as a freelancer outside Morocco, Your daily gross wage in USD is:"
    choices:
      - "< 200"
      - "200 - 500"
      - "500 - 1 000"
      - "1 000 - 2 000"
      - "2 000 - 3 000"
      - "3 000 - 5 000"
      - "5 000 - 10 000"
      - "> 10 000"

  - label: What characteristics would mostly influence your decision to choose one job offer over another?
    required: true
    multiple: true
    choices:
      - Languages, frameworks, and other technologies I’d be working on
      - Office environment or company culture
      - Flexible time or schedule
      - Opportunities for professional development
      - Remote work options
      - How widely used or impactful my work output would be
      - The industry that I’d be working in
      - Company paid training and certifications
      - Salary

  - label: What type of company do you prefer?
    required: true
    choices:
      - Self-employed
      - Company under 10 employees
      - Company between 11 and 30 employees
      - Company between 31 and 100 employees
      - Company above 100 employees

  - label: What agile software development methodology do you use in your team, if any?
    choices:
      - Scrum
      - Kanban
      - XP
      - Other
      - None

  - label: As more companies looking into opening their offices, What options are provided by your employer?
    choices:
      - Back to office
      - Full remote
      - Hybrid

  - label: After COVID-19, What is your preferred mode of working?
    required: true
    choices:
      - In the office
      - Full remote
      - Part-time remote

```
</details>
<details>
  <summary>Tech</summary>

```yaml
title: Tech
label: tech
position: 4
questions:
  - label: "What are the programming languages you like the most?"
    required: true
    multiple: true
    choices:
      - JavaScript
      - HTML/CSS 😉
      - SQL
      - Python
      - Java
      - Bash/Shell/PowerShell
      - C#
      - PHP
      - TypeScript
      - C++
      - C
      - Go
      - Kotlin
      - Ruby
      - Assembly
      - VBA
      - Swift
      - R
      - Rust
      - Objective-C
      - Dart
      - Scala
      - Perl
      - Haskell
      - Julia
      - Other

  - label: "What are the programming languages you want to learn next?"
    required: true
    multiple: true
    choices:
      - JavaScript
      - HTML/CSS 😉
      - SQL
      - Python
      - Java
      - Bash/Shell/PowerShell
      - C#
      - PHP
      - TypeScript
      - C++
      - C
      - Go
      - Kotlin
      - Ruby
      - Assembly
      - VBA
      - Swift
      - R
      - Rust
      - Objective-C
      - Dart
      - Scala
      - Perl
      - Haskell
      - Julia
      - Other

  - label: "What are the programming languages you are using on a daily basis?"
    required: true
    multiple: true
    choices:
      - JavaScript
      - HTML/CSS  😉
      - SQL5
      - Python
      - Java
      - Bash/Shell/PowerShell
      - C#
      - PHP
      - TypeScript
      - C++
      - C
      - Go
      - Kotlin
      - Ruby
      - Assembly
      - VBA
      - Swift
      - R
      - Rust
      - Objective-C
      - Dart
      - Scala
      - Perl
      - Haskell
      - Julia
      - Other

  - label: "What are the front-end frameworks/libraries you are using on a daily basis?"
    multiple: true
    choices:
      - jQuery
      - React.js
      - Angular
      - Vue.js
      - Angular.js
      - Gatsby
      - Ember.js
      - Backbone.js
      - Preact
      - Next.js
      - Svelte
      - Foundation
      - Alpine.js
      - Remix
      - Solid.js
      - Other

  - label: "What are the front-end frameworks/libraries you want to learn next?"
    multiple: true
    choices:
      - jQuery
      - React.js
      - Angular
      - Vue.js
      - Angular.js
      - Gatsby
      - Ember.js
      - Backbone.js
      - Preact
      - Next.js
      - Svelte
      - Foundation
      - Alpine.js
      - Remix
      - Solid.js
      - Other

  - label: "What are the backend frameworks you are using on a daily basis?"
    multiple: true
    choices:
      - .NET
      - Spring Ecosystem
      - Micronaut
      - Quarkus
      - Jakarta EE / Java EE
      - Django
      - Flask
      - Laravel
      - Symfony
      - Ruby on Rails
      - Sinatra
      - FastAPI
      - Express.js
      - Nest.js
      - Sails.js
      - Serverless framework
      - Serverless technology (Vercel,Netlify...)
      - Headless CMS (Strapi,KeystoneJS,Ghost ...)
      - Other

  - label: "What are the backend frameworks you want to learn next?"
    multiple: true
    choices:
      - .NET
      - Spring Ecosystem
      - Micronaut
      - Quarkus
      - Jakarta EE / Java EE
      - Django
      - Flask
      - Laravel
      - Symfony
      - Ruby on Rails
      - Sinatra
      - FastAPI
      - Express.js
      - Nest.js
      - Sails.js
      - Serverless framework
      - Serverless technology (Vercel,Netlify...)
      - Headless CMS (Strapi,KeystoneJS,Ghost ...)
      - Other

  - label: "What are the platforms and tools you are using on a daily basis?"
    required: true
    multiple: true
    choices:
      - Node.js
      - .NET
      - JVM
      - PHP
      - GraalVM
      - Pandas
      - TensorFlow
      - Docker
      - Kubernetes
      - React Native
      - Unity 3D
      - Configuration Management(Ansible, Puppet...)
      - Flutter
      - Terraform
      - Keras
      - Cordova
      - Xamarin
      - Apache Spark
      - Torch/PyTorch
      - Other

  - label: "What are the platforms and tools you want to learn next?"
    required: true
    multiple: true
    choices:
      - Node.js
      - .NET
      - JVM
      - PHP
      - GraalVM
      - Pandas
      - TensorFlow
      - Docker
      - Kubernetes
      - React Native
      - Unity 3D
      - Configuration Management(Ansible, Puppet...)
      - Flutter
      - Terraform
      - Keras
      - Cordova
      - Xamarin
      - Apache Spark
      - Torch/PyTorch
      - Other

  - label: "Your primary Operating System is:"
    required: true
    choices:
      - Windows
      - MacOS
      - Linux-based
      - Windows + WSL2

  - label: "What is you current IDE or code editor for daily work?"
    required: true
    multiple: true
    choices:
      - Jetbrains (IntelliJ, PhpStorm, Resharper ...)
      - VS Code
      - Eclipse
      - Netbeans
      - Vim
      - Sublime
      - Atom
      - Notepad++
      - Cloud based IDE
      - Other

  - label: "How frequently do you learn a new programing language or framework?"
    required: true
    choices:
      - Every few months
      - Once a year
      - Once every few years
      - Once a decade

  - label: "What do you do when you get stuck on a problem?"
    required: true
    multiple: true
    choices:
      - Google it
      - Dig in StackOverflow
      - Do other work and come back later
      - Watch help/tutorial videos
      - Call a coworker or friend

  - label: "The production environment you or your team are using is:"
    multiple: true
    choices:
      - Public cloud (AWS/Azure/GCP/Oracle/IBM/etc.)
      - On-premise
      - Hybrid Cloud
      - Shared hosting
      - Managed PaaS (heroku, app platform, Salesforce, AWS Beanstalk ...)

  - label: "What cloud platform are you using?"
    multiple: true
    choices:
      - GCP
      - AWS
      - Azure
      - Oracle Cloud
      - IBM Cloud
      - DigitalOcean
      - Other Moroccan Cloud providers
      - Other cloud providers
      - None

  - label: "The production database you or your team are using is:"
    multiple: true
    choices:
      - Oracle Database
      - Mysql/MariaDB
      - PostgreSQL
      - SQL Server
      - CosmosDB
      - MongoDB
      - Redis
      - DynamoDB
      - Neo4j
      - Apache Cassandra
      - BigTable
      - Other
  - label: "How often do you use AI tools for Dev (Github Copilot, ChatGPT ...) "
    required: true
    choices:
      - Daily
      - Tried them but not interested
      - Never

```
</details>

<details>
  <summary>Community</summary>

```yaml
title: Community
label: community
position: 5
questions:
  - label: "How far are you involved in any local developer’s community?"
    required: true
    multiple: false
    choices:
      - No, I am not interested
      - I know some, but not involved
      - I am following some communities
      - I am an active member
      - I am an organizer

  - label: "Did you ever participate in an open-source project?"
    required: true
    multiple: true
    choices:
      - I don’t have an account on Github (or alternatives).
      - Yes, only few PRs in various projects.
      - I am maintaining my own project.
      - I have a repo with more than +1k stars.
      - I maintain an organization project with +1k stars.

  - label: "Did you get the chance to write blog posts?"
    required: true
    choices:
      - No, I am not interested.
      - Still thinking about it.
      - Yes, less than 10 blog posts.
      - Yes, more than 10 blog posts.

  - label: "When it comes to IT, what is your primary social network?"
    required: true
    multiple: false
    choices:
      - Facebook
      - Instagram
      - WhatsApp
      - Twitter
      - Youtube
      - Telegram
      - Discord
      - Slack
      - Gitter
      - Reddit
      - None

  - label: "How many IT events did you attend in the last 12 months?"
    required: true
    choices:
      - "0"
      - "1-3"
      - "More than 3"

  - label: "How many talks did you participate in the last 12 months?"
    required: true
    choices:
      - "0"
      - "1 - 3 talks"
      - "More than 3"

  - label: "Do you prefer?"
    required: true
    choices:
      - Live/online events
      - In-person events?
      - Li ja bismillah

  - label: "How do you evaluate the Moroccan Tech Community?"
    required: true
    choices:
      - Bad
      - Not Bad
      - Good
      - Excellent

```
</details>

<br/>
<br/>

Go through the questions and last year's report and:

- If you have a question that you think should be added to the survey, please add it in the comments.
- If you discover a typo or error in the question or answers, please inform us in the comments. We will make sure to fix it before the survey goes live (no need to create a PR for it).
- If you think a question is no longer relevant and needs to be deleted, please let us know in the comments.
- If you think a question or answer is not clear enough and needs to be rephrased, please let us know in the comments.
- For some questions, [many participants chose "Other" option last year](https://stateofdev.ma/). If you think of options that should be added to the possible answers, please let us know in the comments.
- Check other people's suggestions and upvote them. reply for additional details.

- Share this discussion with your friends and colleagues and invite them to participate in the discussion. More people means more ideas and more perspectives.

### 🚀 Improving Survey Reach and Participation

We want to make sure that the survey reaches as many developers as possible, so if you have any suggestions or people we should reach out to, please let us know in the comments.

> ⚠️ Note: Please add one suggestion per comment for easy tracking, voting, and discussion.

**Comment by yjose** [comment]
```yaml
  - label: As more companies looking into opening their offices, What options are provided by your employer?
    choices:
      - Back to office
      - Full remote
      - Hybrid
  ```
I think we should update the question to: `As most companies return to their offices, what options are provided by your employer?`

**Reply by aboullaite** [reply]
I agree

**Comment by aboullaite** [comment]
>  `What is your occupation?`

Maybe Add prompt engineer ? Also using this to capture any suggestion to the list

**Reply by slzakaria** [reply]
While you are at it, i wanna see if there's platform engineers or cloud engineers too !

**Reply by aboullaite** [reply]
Great catch. also SRE

**Reply by nfaihi** [reply]
CRM also, could be an option

**Comment by aboullaite** [comment]
```yaml
  - label: Where did you study coding?
    required: true
    multiple: true
    choices:
      - Self-taught
      - University / Public school
      - Private school
      - Vocational School (bootcamps, technical skills  ...)
      - Other
      ```
      
   This question is very tricky and most people consider themselves as self taught even if they studied it in school! I suggest to replace it with `First contact with programming was in ....` Or just remove as it kind feel duplicate with diploma question

**Reply by Wafwaf14** [reply]
yeah ! totally agree most of people may say self learning , which is almost of the time is right , but in my case yes im really self learning , while i spend the last 3 years learning by my own at home during working as a store manager which is a deferent field or domain

**Reply by aboullaite** [reply]
indeed. Best of luck Wafaa, keep inspiring

**Reply by yjose** [reply]
The problem was that we allowed multi-select for this question. I will update it to accept one answer as well as add more details to self-taught option
- self-taught (no diploma or other fields diploma)

**Comment by aboullaite** [comment]
```
  - label: If you think we have a problem with our education system, from your point of view, who are the main contributors?
    required: true
    multiple: true
    choices:
      - Students level
      - Teachers proficiency
      - Academic defined subjects (system)
      - Lack of private sector/academia collaboration
   ```
I vote for removing this question. It needs a study on its own maybe

**Reply by Wafwaf14** [reply]
Actually my answer maybe be deferent , i start my education in an other country " while we are studying in our mother tongue we have a better level in education " so i guess this is the main problem in the education system

**Comment by aboullaite** [comment]
Couple of improvements:
+ `How often do you work overtime or beyond the formal time expectation of your job?` Should be maybe `normal` instead of `formal`
+ `Employed full-time` to `Full time employee`
+ `Do you work on a side project?` to `Do you work on side projects?`
+ `If you are working full-time contract in Morocco(CDI), Your NET salary range per month in MAD is` to `If you are a full time employee in Morocco(CDI), Your NET salary range per month in MAD is`
+ `If you are working as a freelancer outside Morocco, Your daily gross wage in USD ` to `If you are working as a freelancer/contractor outside Morocco, Your daily gross wage in USD is`
+ `After COVID-19, What is your preferred mode of working?` straight to `What is your preferred mode of working?`

**Comment by aboullaite** [comment]
Maybe add some questions in tech about LLMs
+ Do you use smart coding assistant (such as Github copilot) -> yes/ no
+ If yes, How much are they improving your productivity (options from notch much to very much )
+ How frequent are you asking LLMs tools (such us chatgpt) to solve some of your tasks (scale from not at all to very much)
+ Do you think AI will replace us ? (Yes / No)

**Reply by Wafwaf14** [reply]
yes i use GitHub , recently
not that much maybe i still do not know how to use it 
not at all 
hhh absolutely not !

**Comment by aboullaite** [comment]
For `What are your preferred platforms for learning?` add chatgpt as an option :)

**Reply by Wafwaf14** [reply]
I don't know much of them but i use Coursera , Suggest others if any^

**Comment by soub4i** [comment]
Thinking about adding a property to show a short version of the question in the playground. so instead of showing the full question we can show only the `legend` (eg. Work mode)

```
 - label: As more companies looking into opening their offices, What options are provided by your employer?
 -  legend: Work mode
    choices:
      - Back to office
      - Full remote
      - Hybrid
```

<img width="1203" alt="image" src="https://github.com/geeksblabla/stateofdev.ma/assets/11523791/15a76b6b-663e-4e55-a7c7-f636b13dfd79">

**Reply by yjose** [reply]
We can work on this while preparing results

**Comment by Toufa7** [comment]
I'm suggesting a new question 
```
- Label: Which industry do you currently work in as a developer?
- Label: Which industry are you looking to work in as a developer?
  required: true
  choices:
        - Consulting
        - IT Services
        - Finance
        - Healthcare
        - E-commerce
        - Education
        - ...
```

**Reply by yjose** [reply]
@Toufa7, can you please provide further elaboration on this? Are you suggesting a new question or proposing an update to the existing one?

**Comment by merouanezouaid** [comment]
Just a suggestion..

Can the website have a darija section, where all the questions and answers are in darija?

This is because i heard ppl who really wanna contribute but can't understand english that much 

i know they need to learn english since it's the tech language, but i don't think they should be excluded from the survey

also b darija the website would be catchy like [the moroccan design survey](https://www.whodesign.ma/))

**Reply by aboullaite** [reply]
While we would love to, it is a lot of work! We welcome contribution if anyone want to take a stab at it tho, but as it stands, we can't unfortunately commit to that this year. 
My advice to your friends is to use translation tools for it. Language should not be a barrier.

**Reply by yjose** [reply]
Thank @merouanezouaid as @aboullaite mentioned, Unfortunately, we can't make it for this year.  But should be ready next year and this time for sure 😂

**Comment by AymaneHrouch** [comment]
```
  - label: "How often do you use AI tools for Dev (Github Copilot, ChatGPT ...) "
    required: true
    choices:
      - Daily
      - Tried them but not interested
      - Never
```
We need more choices here.
