### DISCUSSION TITLE
🙌 State of Dev 2024 Call for Questions and Suggestions 🇲🇦🚀

### DISCUSSION THREAD

**Discussion by yjose** [DevC-Casa/stateofdev.ma#119] [Ideas]
The State of Dev in Morocco 2024 is coming up, and we want to hear from you! We're looking for new questions and suggestions, as well as recommendations to improve survey reach and participation for this year's edition

This discussion will be open until September 26, 2024. After that, we will do our best to review suggestions and apply them to ensure that we can open the survey ASAP

##  🙌 How you can help ?

First of all, we want to thank you for your interest in helping us improve the State of Dev in Morocco. and here are some ways you can help:

###  ⁉️ Survey Questions and Answers

[State of Dev in Morocco 2023 Report](https://stateofdev.ma/)

Last Year's Survey Questions and Answers 👇

<details>
  <summary>Profile</summary>

```yaml
title: Profile
label: profile
position: 1
questions:
  - label: What is your gender?
    required: true
    multiple: false
    choices:
      - Male
      - Female

  - label: What is your age?
    required: true
    choices:
      - Younger than 18 years
      - 18 to 24 years
      - 25 to 34 years
      - 35 to 44 years
      - 45 or older

  - label: Where are you currently located?
    required: true
    choices:
      - "Rabat-Salé-Kénitra"
      - "Casablanca-Settat"
      - "Marrakech-Safi"
      - "Tanger-Tétouan-Al Hoceïma"
      - "L'Oriental"
      - "Fès-Meknès"
      - "Béni Mellal-Khénifra"
      - "Drâa-Tafilalet"
      - "Souss-Massa"
      - "Guelmim-Oued Noun"
      - "Laâyoune-Sakia El Hamra"
      - "Dakhla-Oued Ed Dahab"
      - Europe
      - "US & Canada"
      - "Middle East"
      - Others

  - label: What is your occupation?
    required: true
    choices:
      - Back-end developer
      - Full-stack developer
      - Front-end developer
      - Desktop applications developer
      - Mobile developer
      - Embedded applications/devices developer
      - QA/test Developer
      - Game/graphics Developer
      - DevOps specialist
      - Database administrator
      - Designer
      - System administrator
      - Data/business analyst
      - Data scientist or machine learning specialist
      - Data engineer
      - Academic researcher
      - Educator
      - Engineering manager
      - Product manager
      - Scientist
      - Site reliability engineer
      - Senior executive/VP
      - Marketing/sales professional
      - Network engineer
      - Security specialist
      - IT specialist
      - Prompt engineer
      - ERP Consultant

  - label: What is your highest diploma?
    required: true
    choices:
      - Self-taught
      - Bac +2/+3, Bachelor’s degree (B.A., B.S., B.Eng., etc.)
      - Bac +5, Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
      - Bac +8, Other doctoral degree (Ph.D., Ed.D., etc.)

  - label: How many years have you been coding professionally?
    required: true
    choices:
      - "I don't have any professional coding experience"
      - Less than a year
      - 1-2 years
      - 3-4 years
      - 5-6 years
      - 7-10 years
      - 11-16 years
      - 16+ years

  - label: Is coding a hobby for you?
    required: true
    choices:
      - Yes
      - No

  - label: Do you have any plans to work outside Morocco?
    required: true
    choices:
      - Yes, in the next 12 months
      - Yes, in the next 24 months
      - Still hesitating
      - Currently working outside Morocco
      - No

  - label: If you are working abroad, do you have any plans to come back to Morocco?
    choices:
      - Yes
      - Still hesitating
      - No

  - label: What do you usually drink while coding?
    required: true
    choices:
      - Tea
      - Coffee
      - Water
      - Energy drinks
      - None
      - Other
```

</details>

<details>
  <summary>Learning & Education</summary>

```yaml
title: Learning & Education
label: education
position: 2
questions:
  - label: Where did you study coding?
    required: true
    choices:
      - Self-taught (no diploma or other field's diploma).
      - University / Public school
      - Private school
      - Vocational School (bootcamps, technical skills  ...)
      - Coding schools (1337, YouCode, etc.)
      - Other

  - label: Do you think school gives you enough knowledge to start your professional career?
    required: false
    choices:
      - Not enough
      - Enough to start
      - Everything I needed

  - label: What languages can you read/write?
    required: true
    multiple: true
    choices:
      - Arabic
      - Amazigh
      - French
      - English
      - Others

  - label: Is English an obstacle to learning new technologies?
    required: true
    choices:
      - Yes
      - No

  - label: Do you think we need more content in Darija?
    required: true
    choices:
      - Spoken
      - Written/Read
      - Both
      - No

  - label: What are your preferred platforms for learning?
    required: true
    multiple: true
    choices:
      - YouTube
      - Paid platforms
      - Books
      - Official documentation
      - Blog posts
      - Company resources
      - Conferences (virtual/in-person)
      - Podcasts
      - Online Communities (StackOverflow/Reddit/Twitter)
      - AI Assistant (ChatGPT, etc)
      - Others
```
</details>

<details>
  <summary>Work</summary>

```yaml
title: Work
label: work
position: 3
questions:
  - label: "What is your employment status?"
    required: true
    multiple: false
    choices:
      - Founder/entrepreneur
      - Full-time employee
      - Freelancer/self-employed
      - Part-time employee
      - Looking for work
      - Internship
      - Student

  - label: How often do you work overtime or beyond the normal time expectation of your job?
    choices:
      - Never
      - "Rarely: 1-2 days per year or less "
      - "Occasionally: 1-2 days per quarter but less than monthly "
      - "Sometimes: 1-2 days per month but less than weekly"
      - "Often: 1-2 days per week or more"

  - label: How do you feel about your job?
    choices:
      - Very Unsatisfied
      - Slightly Unsatisfied
      - Neither satisfied nor Unsatisfied
      - Slightly satisfied
      - Very satisfied

  - label: Do you work on side projects?
    required: true
    choices:
      - No
      - Yes For profit
      - Yes For learning

  - label: How long have you been unemployed after graduation?
    choices:
      - None, I worked straight after my graduation 😎
      - Up to 3 months
      - Up to 6 months
      - Up to 1 year
      - More than 1 year

  - label: "If you are a full time employee in Morocco(CDI), Your NET salary range per month in MAD is:"
    choices:
      - "< 4 000"
      - "4 000 - 6 000"
      - "6 000 - 8 000"
      - "8 000 - 10 000"
      - "10 000 - 12 000"
      - "12 000 - 14 000"
      - "14 000 - 16 000"
      - "16 000 - 18 000"
      - "18 000 - 20 000"
      - "20 000 - 22 000"
      - "22 000 - 25 000"
      - "25 000 - 30 000"
      - "> 30 000"

  - label: "If you are working as a freelancer in Morocco, Your salary range per day in MAD(TJM) is:"
    choices:
      - "< 1 000"
      - "1 000 - 1 500"
      - "1 500 - 2 000"
      - "2 000 - 2 500"
      - "2 500 - 3 000"
      - "3 000 - 4 000"
      - "4 000 - 5 000"
      - "> 5 000"

  - label: "If you are working full-time contract outside Morocco, Your gross salary range per year in USD is:"
    choices:
      - "< 20 000"
      - "20 000 - 25 000"
      - "30 500 - 40 000"
      - "40 000 - 50 000"
      - "50 000 - 60 000"
      - "60 000 - 80 000"
      - "80 000 - 100 000"
      - "100 000 - 120 000"
      - "120 000 - 150 000"
      - "150 000 - 200 000"
      - "> 200 000"

  - label: "If you are working as a freelancer/contractor outside Morocco, Your daily gross wage in USD is:"
    choices:
      - "< 200"
      - "200 - 500"
      - "500 - 1 000"
      - "1 000 - 2 000"
      - "2 000 - 3 000"
      - "3 000 - 5 000"
      - "5 000 - 10 000"
      - "> 10 000"

  - label: What characteristics would mostly influence your decision to choose one job offer over another?
    required: true
    multiple: true
    choices:
      - Languages, frameworks, and other technologies I’d be working on
      - Office environment or company culture
      - Flexible time or schedule
      - Opportunities for professional development
      - Remote work options
      - How widely used or impactful my work output would be
      - The industry that I’d be working in
      - Company paid training and certifications
      - Salary

  - label: What type of company do you prefer?
    required: true
    choices:
      - Self-employed
      - Company under 10 employees
      - Company between 11 and 30 employees
      - Company between 31 and 100 employees
      - Company above 100 employees

  - label: What agile software development methodology do you use in your team, if any?
    choices:
      - Scrum
      - Kanban
      - XP
      - Other
      - None

  - label: As many companies are returning to their offices, what options does your employer provide?
    choices:
      - Back to office
      - Full remote
      - Hybrid

  - label: What is your preferred mode of work?
    required: true
    choices:
      - From the office
      - Full remote
      - Part-time remote/Hybrid

```
</details>

<details>
  <summary>AI</summary>

```yaml
title: AI
label: ai
position: 4
questions:
  - label: "How often do you use AI tools for Dev (Github Copilot, ChatGPT ...) "
    required: true
    choices:
      - Daily
      - Occasionally
      - Tried them but not interested
      - Never

  - label: "If you are using AI based coding assistants for Dev, How much improvement do you see in your productivity?"
    choices:
      - Did not improve my productivity
      - Somewhat improved my productivity (5% to 10%)
      - Helped me to become more productive (10% to 30%)
      - I am now very productive (30% to 50%)
      - I am a 10x engineer now (+50%)

  - label: "Do you think AI will replace developers in the future?"
    required: true
    choices:
      - Not very much ( less than 10% )
      - Somewhat ( 10% - 30% )
      - To some extent ( 30% - 50% )
      - The majority ( 50% - 80% )
      - Completely  ( more than 80% )
      - Not sure

  - label: "Are you planning to learn AI to build apps?"
    required: true
    choices:
      - No, I am not interested
      - Already started learning the basics.
      - I can build simple apps with AI using third-party APIs.
      - I can build complex apps and play with models.
      - I am already an expert

  - label: "How much is your company investing in AI?"
    choices:
      - We haven't started adopting AI
      - We're getting the basics in place
      - We have some ad-hoc use cases in production
      - We have several use cases in production

  - label: "Which AI tools and apps do you use?"
    multiple: true
    choices:
      - ChatGPT
      - Bard (Google)
      - Claude (Anthropic)
      - DALL-E (OpenAI)
      - GitHub Copilot
      - QuillBot
      - Notion AI
      - Midijourney
      - Coby.ai
      - Grammarly
      - Other

  - label: "Which AI frameworks and models do you use?"
    multiple: true
    choices:
      - LangChain
      - Hugging Face
      - AWS Bedrock
      - Together.ai
      - Weights & Biases
      - Llama
      - Haystack
      - Humanloop
      - Unstructured
      - PyTorch
      - TensorFlow
      - OpenAI (GPT)
      - Keras
      - Microsoft Cognitive Toolkit
      - Caffe
      - Mistral
      - PyBrain
      - IBM Watson
      - Scikit-Learn
      - Other

```
</details>
<details>
  <summary>Tech</summary>

```yaml
title: Tech
label: tech
position: 5
questions:
  - label: "What are the programming languages you like the most?"
    required: true
    multiple: true
    choices:
      - JavaScript
      - HTML/CSS 😉
      - SQL
      - Python
      - Java
      - Bash/Shell/PowerShell
      - C#
      - PHP
      - TypeScript
      - C++
      - C
      - Go
      - Kotlin
      - Ruby
      - Assembly
      - VBA
      - Swift
      - R
      - Rust
      - Objective-C
      - Dart
      - Scala
      - Perl
      - Haskell
      - Julia
      - Other

  - label: "What are the programming languages you want to learn next?"
    required: true
    multiple: true
    choices:
      - JavaScript
      - HTML/CSS 😉
      - SQL
      - Python
      - Java
      - Bash/Shell/PowerShell
      - C#
      - PHP
      - TypeScript
      - C++
      - C
      - Go
      - Kotlin
      - Ruby
      - Assembly
      - VBA
      - Swift
      - R
      - Rust
      - Objective-C
      - Dart
      - Scala
      - Perl
      - Haskell
      - Julia
      - Other

  - label: "What are the programming languages you are using on a daily basis?"
    required: true
    multiple: true
    choices:
      - JavaScript
      - HTML/CSS  😉
      - SQL5
      - Python
      - Java
      - Bash/Shell/PowerShell
      - C#
      - PHP
      - TypeScript
      - C++
      - C
      - Go
      - Kotlin
      - Ruby
      - Assembly
      - VBA
      - Swift
      - R
      - Rust
      - Objective-C
      - Dart
      - Scala
      - Perl
      - Haskell
      - Julia
      - Other

  - label: "What are the front-end frameworks/libraries you are using on a daily basis?"
    multiple: true
    choices:
      - jQuery
      - React.js
      - Angular
      - Vue.js
      - Angular.js
      - Gatsby
      - Ember.js
      - Backbone.js
      - Preact
      - Next.js
      - Svelte
      - Foundation
      - Alpine.js
      - Remix
      - Solid.js
      - AstroJs
      - Qwik
      - Htmx
      - Other

  - label: "What are the front-end frameworks/libraries you want to learn next?"
    multiple: true
    choices:
      - jQuery
      - React.js
      - Angular
      - Vue.js
      - Angular.js
      - Gatsby
      - Ember.js
      - Backbone.js
      - Preact
      - Next.js
      - Svelte
      - Foundation
      - Alpine.js
      - Remix
      - Solid.js
      - Astro Js
      - Qwik
      - Htmx
      - Other

  - label: "What approach do you use for styling your web apps?"
    multiple: true
    choices:
      - CSS
      - CSS Frameworks (Bootstrap, Material UI ...)
      - CSS in JS (Styled Components, Emotion ...)
      - CSS Preprocessor (Sass, Less ...)
      - CSS Modules
      - Tailwind CSS
      - Other

  - label: "What are the backend frameworks you are using on a daily basis?"
    multiple: true
    choices:
      - .NET
      - Spring Ecosystem
      - Micronaut
      - Quarkus
      - Jakarta EE / Java EE
      - Django
      - Flask
      - Laravel
      - Symfony
      - Ruby on Rails
      - Sinatra
      - FastAPI
      - Express.js
      - Nest.js
      - Sails.js
      - Serverless framework
      - Serverless technology (Vercel,Netlify...)
      - Headless CMS (Strapi,KeystoneJS,Ghost ...)
      - Other

  - label: "What are the backend frameworks you want to learn next?"
    multiple: true
    choices:
      - .NET
      - Spring Ecosystem
      - Micronaut
      - Quarkus
      - Jakarta EE / Java EE
      - Django
      - Flask
      - Laravel
      - Symfony
      - Ruby on Rails
      - Sinatra
      - FastAPI
      - Express.js
      - Nest.js
      - Sails.js
      - Serverless framework
      - Serverless technology (Vercel,Netlify...)
      - Headless CMS (Strapi,KeystoneJS,Ghost ...)
      - Other

  - label: "What are the platforms and tools you are using on a daily basis?"
    required: true
    multiple: true
    choices:
      - Node.js
      - .NET
      - JVM
      - PHP
      - GraalVM
      - Pandas
      - TensorFlow
      - Docker
      - Kubernetes
      - React Native
      - Unity 3D
      - Configuration Management(Ansible, Puppet...)
      - Flutter
      - Terraform
      - Cordova
      - Xamarin
      - Apache Spark
      - Bun Js
      - Deno Js
      - Other

  - label: "What are the platforms and tools you want to learn next?"
    required: true
    multiple: true
    choices:
      - Node.js
      - .NET
      - JVM
      - PHP
      - GraalVM
      - Pandas
      - TensorFlow
      - Docker
      - Kubernetes
      - React Native
      - Unity 3D
      - Configuration Management(Ansible, Puppet...)
      - Flutter
      - Terraform
      - Cordova
      - Xamarin
      - Apache Spark
      - Bun Js
      - Deno Js
      - Other

  - label: "Your primary Operating System is:"
    required: true
    choices:
      - Windows
      - MacOS
      - Linux-based
      - Windows + WSL2

  - label: "What is you current IDE or code editor for daily work?"
    required: true
    multiple: true
    choices:
      - Jetbrains (IntelliJ, PhpStorm, Resharper ...)
      - VS Code
      - Eclipse
      - Netbeans
      - Vim
      - Sublime
      - Atom
      - Notepad++
      - Cloud based IDE
      - Other

  - label: "How frequently do you learn a new programming language or framework?"
    required: true
    choices:
      - Every few months
      - Once a year
      - Once every few years
      - Once a decade

  - label: "What do you do when you get stuck on a problem?"
    required: true
    multiple: true
    choices:
      - Google it
      - Ask ChatGPT or other AI assistants
      - Dig in StackOverflow
      - Do other work and come back later
      - Watch help/tutorial videos
      - Call a coworker or friend

  - label: "The production environment you or your team are using is:"
    multiple: true
    choices:
      - Public cloud (AWS/Azure/GCP/Oracle/IBM/etc.)
      - On-premise
      - Hybrid Cloud
      - Shared hosting
      - Managed PaaS (heroku, app platform, Salesforce, AWS Beanstalk ...)

  - label: "What cloud platform are you using?"
    multiple: true
    choices:
      - GCP
      - AWS
      - Azure
      - Oracle Cloud
      - IBM Cloud
      - DigitalOcean
      - Other Moroccan Cloud providers
      - Other cloud providers
      - None

  - label: "The production database you or your team are using is:"
    multiple: true
    choices:
      - Oracle Database
      - Mysql/MariaDB
      - PostgreSQL
      - SQL Server
      - CosmosDB
      - MongoDB
      - Redis
      - DynamoDB
      - Neo4j
      - Apache Cassandra
      - BigTable
      - Other

```
</details>

<details>
  <summary>Community</summary>

```yaml
title: Community
label: community
position: 6
questions:
  - label: "How far are you involved in any local developer’s community?"
    required: true
    multiple: false
    choices:
      - No, I am not interested
      - I know some, but not involved
      - I am following some communities
      - I am an active member
      - I am an organizer

  - label: "Did you ever participate in an open-source project?"
    required: true
    multiple: true
    choices:
      - I don’t have an account on Github (or alternatives).
      - Yes, only few PRs in various projects.
      - I am maintaining my own project.
      - I have a repo with more than +1k stars.
      - I maintain an organization project with +1k stars.

  - label: "Did you get the chance to write blog posts?"
    required: true
    choices:
      - No, I am not interested.
      - Still thinking about it.
      - Yes, less than 10 blog posts.
      - Yes, more than 10 blog posts.

  - label: "When it comes to IT, what is your primary social network?"
    required: true
    multiple: false
    choices:
      - Facebook
      - Instagram
      - WhatsApp
      - Twitter
      - Youtube
      - Telegram
      - Discord
      - Slack
      - Gitter
      - Reddit
      - LinkedIn
      - None

  - label: "How many IT events did you attend in person in the past 12 months?"
    required: true
    choices:
      - "0"
      - "1-3"
      - "More than 3"

  - label: "How many talks did you participate in the last 12 months?"
    required: true
    choices:
      - "0"
      - "1 - 3 talks"
      - "More than 3"

  - label: "Do you prefer?"
    required: true
    choices:
      - Live/online events
      - In-person events?
      - Li ja bismillah

  - label: "How do you evaluate the Moroccan Tech Community?"
    required: true
    choices:
      - Bad
      - Not Bad
      - Good
      - Excellent

```
</details>

<br/>
<br/>

Go through the questions and last year's report and:

- If you have a question that you think should be added to the survey, please add it in the comments.
- If you discover a typo or error in the question or answers, please inform us in the comments. We will make sure to fix it before the survey goes live (no need to create a PR for it).
- If you think a question is no longer relevant and needs to be deleted, please let us know in the comments.
- If you think a question or answer is not clear enough and needs to be rephrased, please let us know in the comments.
- For some questions, [many participants chose "Other" option last year](https://stateofdev.ma/). If you think of options that should be added to the possible answers, please let us know in the comments.
- Check other people's suggestions and upvote them. reply for additional details.

- Share this discussion with your friends and colleagues and invite them to participate in the discussion. More people means more ideas and more perspectives.

### 🚀 Improving Survey Reach and Participation

We want to make sure that the survey reaches as many developers as possible, so if you have any suggestions or people we should reach out to, please let us know in the comments.

> [!IMPORTANT]
>  Please add one suggestion per comment for easy tracking, voting, and discussion.
